#!/bin/bash

##
## A script for uploading the georanks output to s3 (for use by geowhiz or
## anyone who wants it).
##
## Run as: ./deploy /path/to/georanks.txt
##

if [ $# -eq 0 ]
then
  echo "No arguments supplied"
  echo
  echo "Usage: ./deploy /path/to/georanks.txt"
  exit 1
fi

set -x

$HOME/.virtualenvs/s3/bin/s3cmd --mime-type="text/plain; charset=utf-8" --acl-public put $1 s3://madelfio-files/georanks.txt
